### ISSUE TITLE
Regex literals?

### ISSUE THREAD

**Issue by glyh** [ciel-lang/CIEL#16]
As title, CL21 provides regex literal, I think it's good to include it in CIEL.

**Comment by vindarel** [comment]
Probably not, because I want to not require reader macros or to modify the readtable, because that requires an addition to Slime to get them working in the editor (see that cl21 requires a cl21.el to be loaded in Emacs to work smoothly), which is not easily portable to other editors (and sometimes there are interferences with other libraries that use cl-interpol or cl-annot at the same time).

Providing an even easier way to use regexs, if useful, yes.

**Comment by glyh** [comment]
OK, I'm closing this.
