### ISSUE TITLE
Should cl+ssl be a dependency?

### ISSUE THREAD

**Issue by simendsjo** [ciel-lang/CIEL#20]
Tried loading ciel, but got an error because cl+ssl wasn't loaded. Noticed your build loads it before ciel, and doing the same, it works locally too. Maybe it should be a dependency for ciel instead of requiring it to be loaded first? Ref https://github.com/ciel-lang/CIEL/commit/50009c23110dcd5a304e5dcfdd78b9d0444093bc#diff-fecd98b737cd152e9adb210295863f35539f5f59c1b76a9408529f00b484a7c5R4

**Comment by vindarel** [comment]
Hi, I am not totally sure how to proceed here. The issue is that we need cl+ssl only to load the asd. We have it in the .asd for the Deploy configuration, used to build a binary.

- in other projects I have put `(require "cl+ssl")` at the asd's top
  - but we still need to have it on our system before
- move the Deploy config outside the asd to build-image.lisp? Now that you speak about it, this seems the way to go: build configuration are at the same place, we can load the .asd to use CIEL as a lisp library from Slime with no hickup.

What's sure is that it isn't enough to add it in `:depends-on`.

thanks

**Comment by vindarel** [comment]
I improved the situation. Maybe we can "quickload" cl+ssl to be sure.

> move the Deploy config outside the asd to build-image.lisp

I was misleaded, build-image.lisp is to build a core image, Deploy is to build the binary,

**Comment by svetlyak40wt** [comment]
@vindarel I've found CIEL is excluded from Ultralisp because of this error:

```
Condition: Error while trying to load definition for system ciel from pathname /tmp/checker/ciel-lang-CIEL/ciel.asd: Don't know how to REQUIRE cl+ssl.
```

You can check the project status on [it's page](https://ultralisp.org/projects/ciel-lang/CIEL) and if there is error, click on the "error" word.

Did you try to specify CL+SSL as a DEFSYSTEM-DEPENDS-ON dependency?

**Comment by vindarel** [comment]
Thanks, Alexander. I didn't try. cl+ssl is needed outside the defsystem, for Deploy:

```lisp
#+linux (deploy:define-library cl+ssl::libssl :dont-deploy T)
```

and is actually needed to load the .asd file, not only the system definition. For my builds, I fix this with a quickload in the Makefile.

What do you think of adding a `(ql:quickload :cl+ssl)` at the top of the .asd ?

**Comment by vindarel** [comment]
I removed the cl+ssl dependency to load the .asd. The base case, raised by @simendsjo, which is loading ciel.asd oneself, should work.

The Ultralisp build is fixed. Does loading it from there works for you all?

**Comment by vindarel** [comment]
https://ultralisp.org/projects/ciel-lang/CIEL
